export { default as HomePage } from './HomePage/HomePage'
export { default as ClassifierPage } from './Classifier/ClassifierPage'
export { default as RecyclingMap } from './Map/RecyclingMap'
export { default as StatsPage } from './Stats/StatsPage'
export { default as ScannerPage } from './Scanner/ScannerPage'
export { default as TermsPage } from './Terms/TermsPage'
export { default as NotFoundPage } from './NotFound/NotFoundPage'
